### ISSUE TITLE
Server error (500) when adding org.21659.admin to /userpermission/63628

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#240] opened 2019-11-07 17:40 UTC
![Screenshot 2019-11-07 18 37 12](https://user-images.githubusercontent.com/16888757/68413225-1c4ccb00-018e-11ea-9c2d-cb3a2d089aee.png)

**Comment by vegu** [comment] 2019-11-07 18:37
Looks like a bug caused by the org affiliationship request without an asn - which is a valid thing to have, but its hard failing because its trying to do asn validation on an empty asn during the save. Looks like this got introduced at some point when we added bogon asn validation.

The cause for this should get a bug ticket in the main repo.

This particular instance can be fixed by typing any number into the asn field and deleting the affiliation request (since its already approved anyways).

cc: @arnoldnipper

**Closed** 2019-11-07 18:46 UTC
